### ISSUE TITLE
Blanks Screen

### ISSUE THREAD

**Issue by FDEthan** [DanTappan/Pi-Kiosk#1]
Pi Zero 2 W 
Screen is showing blank after the normal boot load screen.
I can access the Kiosk control, and functions are working.

**Comment by FDEthan** [comment]
Got it working with midori instead of chromium

**Comment by DanTappan** [comment]
FWIW: I don't have a Pi Zero 2W, but when I tried a Pi Zero W, the latest (Bookworm) release did not support Chromium, but the legacy (Bullseye) did.

**Comment by FDEthan** [comment]
Thanks 😊
Before I found your script I tried bookworm and chromium without success also. 

I ended up re running your script with the Midori browser option and it work next try
